server:
  port: 9011
spring:
  application:
    name: tensquare-manager #指定服务名
eureka:
  client:
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true
zuul: # 网关
  routes: # 路由规则配置
    tensquare-user: # 自己起的路由配置名称(路由配置可以配置多个),注意名称不要重复
      path: /user/** #配置访问网关的路径
      serviceId: tensquare-user # 将请求转发到哪个微服务
    tensquare-base: # 自己起的路由配置名称(路由配置可以配置多个),注意名称不要重复
      path: /base/** #配置访问网关的路径
      serviceId: tensquare-base # 将请求转发到哪个微服务
    tensquare-qa: # 自己起的路由配置名称(路由配置可以配置多个),注意名称不要重复
      path: /qa/** #配置访问网关的路径
      serviceId: tensquare-qa # 将请求转发到哪个微服务
  sensitive-headers: #配置忽略哪些请求头,默认包含Authorization头.
jwt:
  secret: itcast